# Generated by Django 5.2.1 on 2025-06-04 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_catalog', '0002_property_api'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('confirmada', 'CONFIRMADA'), ('cancelada', 'CANCELADA')], default='pendiente', max_length=50)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50)),
                ('notas', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_catalog.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
