# Generated by Django 5.2.1 on 2025-06-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name_plural': 'Listado'},
        ),
        migrations.AlterField(
            model_name='appointments',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
