# Generated by Django 5.2.1 on 2025-06-04 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('propiedad', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('clase_tipo', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('fin_de_obra', models.DateField()),
                ('fase', models.CharField()),
                ('bloqueo', models.CharField()),
                ('proyecto_id', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('parqueos', models.IntegerField()),
                ('m2construccion', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('año', models.BigIntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('detalles', models.CharField()),
                ('descripcion_corta', models.TextField()),
                ('caracteristicas', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=2, max_digits=6)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comision_referencia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comision_directa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_catalog.property')),
            ],
        ),
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_external', models.BigIntegerField()),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('aprobacion12cuotas', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_catalog.property')),
            ],
        ),
    ]
