# Generated by Django 5.2.1 on 2025-06-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='api',
            field=models.BooleanField(default=False),
        ),
    ]
