# Generated by Django 5.2.1 on 2025-06-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_catalog', '0002_property_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyect',
            name='property',
        ),
        migrations.AlterField(
            model_name='property',
            name='proyecto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_catalog.proyect'),
        ),
    ]
