# Generated by Django 5.2.1 on 2025-06-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_catalog', '0004_alter_images_tipo_alter_images_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='precio_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
