# Generated by Django 5.2.1 on 2025-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_catalog', '0005_property_precio_property_precio_sugerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyect',
            name='api',
            field=models.BooleanField(default=False),
        ),
    ]
