# Generated by Django 5.2.1 on 2025-06-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_catalog', '0007_alter_property_comision_directa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='comision_directa',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='comision_referencia',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='precio_sugerido',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
