# Generated by Django 5.2.1 on 2025-06-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_catalog', '0009_alter_property_comision_directa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='proyect',
            options={'verbose_name_plural': 'Proyectos'},
        ),
    ]
